name: Dockerize Java Application

on:
  push:
    branches:
      - docker # Change 'docker' to your branch name where you want to trigger this action (e.g., 'main')
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adoptium"

      - name: Build the application with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/p8:latest .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/p8:latest

      - name: Run Docker container (optional)
        run: |
          docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/p8:latest
