name: Dockerize Java Application

on:
  push:
    branches:
      - docker
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adoptopenjdk"

      - name: Build the application with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t p8 .

      - name: Push Docker image to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push p8

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 p8
